travis:
  secure:
    BINSTAR_TOKEN: pL8c4hYzBNQ8+wsAE5o6wioGwKn6PPAYEUo/DxsdrKm0kL7CQrnBH/UHIF1n+DQR9VXdF8W+bg0LiiLieg1wIAo/O0vy+4hLaYpVXwplWSRxqRTFMSFO0kyM6XYn/cSS9yMIE158aruMd282FMVdZGFGtrUcAPVW41LkEePe2hJFge/DnG0+bFB/fTHDP1PdePe4l1yreVZCV0LfvnpVxfD20Iari2W0ig0DEuPhJ8a8d4+f3J+03JEBCIfsBg+WrOeNT4FUdXCgGbCnxysS5ybWeLyPXU2QijGb1Q/z5Lp6j5NIE+zTcWA67c1KrLB82r2gkllYrd4vmjogSY68sZm4cjVQfKEaFWnFi+lFil9/eIMMzil7xcDF2+5dPpZX03swUXPsEVmfp6QBfrhDeIeP7L3x7759Gj1V2rWuSVhMBQiUg5L/SIW0N9IDgYKE5Q1mkU1fKCbWgbRNfxU7KVaR2wj+y46y7YU2WNISzbamM6U+m+utcs7vB2jb/LRSCmbDh9DUQdCicg/MHe/aAHFS+D4S9ALh6s4BqctFxP3dilS6RQVnPKA+sqnjEbUPeaXJ1N6BnDUwAc30Piksrbrk+40qpsdnamjrM0eXC69RKxRBUFflKGWpUStJAeGegW8HwHFpXbcfsvUTEAVyj2rBIIU+TCUUqCn/fBPAGxM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
